# Generated by Django 4.2.7 on 2026-01-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='vote_type',
            new_name='value',
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_context',
            field=models.CharField(choices=[('feed', 'Feed'), ('profile', 'Profile'), ('leaderboard', 'Leaderboard')], default='feed', max_length=20),
        ),
        migrations.AddField(
            model_name='vote',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
    ]
