# Generated by Django 4.2.7 on 2026-01-05 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='editing_software',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
