# Generated by Django 4.2.7 on 2026-01-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(max_length=500, upload_to='videos/'),
        ),
    ]
