# Generated by Django 4.2.7 on 2026-01-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="The display name (e.g., 'Anime (AMV)')", max_length=100)),
                ('slug', models.SlugField(blank=True, help_text="The URL-friendly name (e.g., 'amv')", unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in the sidebar')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
