# Generated by Django 5.1.3 on 2026-01-25 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g., 'WIP/Feedback' or 'Finished Work'", max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Main Categories',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['main_category', 'order', 'label'], 'verbose_name_plural': 'Subcategories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='label',
            field=models.CharField(help_text="e.g., 'Anime (AMV)', 'Motion Graphics'", max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='posts.maincategory'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('main_category', 'slug')},
        ),
    ]
