# Generated by Django 5.1.3 on 2026-01-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_main_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'label'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='category',
            name='label',
            field=models.CharField(help_text="The display name (e.g., 'Anime (AMV)')", max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in the sidebar'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text="The URL-friendly name (e.g., 'amv')", unique=True),
        ),
        migrations.RemoveField(
            model_name='category',
            name='main_category',
        ),
    ]
