# Generated by Django 5.1.3 on 2026-01-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feedback_wanted',
            field=models.BooleanField(default=False),
        ),
    ]
