# Generated by Django 5.1.3 on 2026-02-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_feedback_wanted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='og_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='og_images/'),
        ),
    ]
