# Generated by Django 5.1.3 on 2026-02-04 00:49

import posts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_og_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='og_image',
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=posts.utils.post_thumbnail_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(max_length=500, upload_to=posts.utils.post_video_path),
        ),
    ]
