# Generated by Django 5.1.3 on 2026-02-04 00:50

from django.db import migrations
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile


def rename_files_to_uuid(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Post = apps.get_model('posts', 'Post')
    
    print("\n=== Starting file migration to UUID-based paths ===\n")
    
    # Migrate user avatars
    print("Migrating user avatars...")
    user_count = 0
    user_errors = 0
    
    for user in User.objects.exclude(avatar='').exclude(avatar=None):
        if not user.avatar:
            continue
            
        old_path = user.avatar.name
        if not old_path:
            continue
        
        # Check if already in new format (UUID-based)
        if old_path.startswith(f'avatars/{user.id}.'):
            print(f"  Skipping {user.username} - already migrated")
            continue
        
        try:
            # Get file extension
            ext = old_path.split('.')[-1].lower()
            new_path = f'avatars/{user.id}.{ext}'
            
            # Read old file
            if not default_storage.exists(old_path):
                print(f"  WARNING: File not found for {user.username}: {old_path}")
                user_errors += 1
                continue
            
            old_file = default_storage.open(old_path, 'rb')
            file_content = old_file.read()
            old_file.close()
            
            # Write to new path
            default_storage.save(new_path, ContentFile(file_content))
            
            # Update database
            user.avatar.name = new_path
            user.save(update_fields=['avatar'])
            
            # Delete old file
            default_storage.delete(old_path)
            
            print(f"  ✓ Migrated {user.username}: {old_path} → {new_path}")
            user_count += 1
            
        except Exception as e:
            print(f"  ERROR migrating {user.username}: {str(e)}")
            user_errors += 1
    
    print(f"\nAvatars: {user_count} migrated, {user_errors} errors\n")
    
    # Migrate post videos
    print("Migrating post videos...")
    video_count = 0
    video_errors = 0
    
    for post in Post.objects.exclude(video='').exclude(video=None):
        if not post.video:
            continue
            
        old_path = post.video.name
        if not old_path:
            continue
        
        # Check if already in new format
        if old_path.startswith(f'videos/{post.id}.'):
            print(f"  Skipping post {post.id} - already migrated")
            continue
        
        try:
            ext = old_path.split('.')[-1].lower()
            new_path = f'videos/{post.id}.{ext}'
            
            if not default_storage.exists(old_path):
                print(f"  WARNING: Video not found for post {post.id}: {old_path}")
                video_errors += 1
                continue
            
            old_file = default_storage.open(old_path, 'rb')
            file_content = old_file.read()
            old_file.close()
            
            default_storage.save(new_path, ContentFile(file_content))
            
            post.video.name = new_path
            post.save(update_fields=['video'])
            
            default_storage.delete(old_path)
            
            print(f"  ✓ Migrated post {post.id}: {old_path} → {new_path}")
            video_count += 1
            
        except Exception as e:
            print(f"  ERROR migrating post {post.id}: {str(e)}")
            video_errors += 1
    
    print(f"\nVideos: {video_count} migrated, {video_errors} errors\n")
    
    # Migrate post thumbnails
    print("Migrating post thumbnails...")
    thumb_count = 0
    thumb_errors = 0
    
    for post in Post.objects.exclude(thumbnail='').exclude(thumbnail=None):
        if not post.thumbnail:
            continue
            
        old_path = post.thumbnail.name
        if not old_path:
            continue
        
        # Check if already in new format
        if old_path.startswith(f'thumbnails/{post.id}.'):
            print(f"  Skipping thumbnail for post {post.id} - already migrated")
            continue
        
        try:
            ext = old_path.split('.')[-1].lower()
            new_path = f'thumbnails/{post.id}.{ext}'
            
            if not default_storage.exists(old_path):
                print(f"  WARNING: Thumbnail not found for post {post.id}: {old_path}")
                thumb_errors += 1
                continue
            
            old_file = default_storage.open(old_path, 'rb')
            file_content = old_file.read()
            old_file.close()
            
            default_storage.save(new_path, ContentFile(file_content))
            
            post.thumbnail.name = new_path
            post.save(update_fields=['thumbnail'])
            
            default_storage.delete(old_path)
            
            print(f"  ✓ Migrated thumbnail for post {post.id}: {old_path} → {new_path}")
            thumb_count += 1
            
        except Exception as e:
            print(f"  ERROR migrating thumbnail for post {post.id}: {str(e)}")
            thumb_errors += 1
    
    print(f"\nThumbnails: {thumb_count} migrated, {thumb_errors} errors\n")
    
    print("=== Migration complete ===")
    print(f"Total: {user_count + video_count + thumb_count} files migrated")
    print(f"Total errors: {user_errors + video_errors + thumb_errors}")


def reverse_migration(apps, schema_editor):
    print("WARNING: Reverse migration not implemented")
    print("Restore from backup if needed")


class Migration(migrations.Migration):
    
    dependencies = [
        ('users', '0004_alter_user_avatar'),
        ('posts', '0012_remove_post_og_image_alter_post_thumbnail_and_more'),
    ]
    
    operations = [
        migrations.RunPython(rename_files_to_uuid, reverse_migration),
    ]