# Generated by Django 5.1.3 on 2026-02-08 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_migrate_file_paths'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('creator_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='users.creatorprofile')),
            ],
            options={
                'ordering': ['display_order'],
                'indexes': [models.Index(fields=['creator_profile', 'display_order'], name='users_socia_creator_7a6e16_idx')],
            },
        ),
    ]
